[package]
name = "strings"
version = "0.1.0"
authors = ["Mark English <mark.english@anaplan.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linked_hash_set = "*"
parameterized = "*"

